name: Feature Request
description: Suggest an improvement or new capability for the integration
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Please describe the problem and the solution you have in mind.

  - type: checkboxes
    id: preflight
    attributes:
      label: Before you submit
      options:
        - label: I have searched the existing issues and this is not a duplicate.
          required: true
        - label: I have reviewed the [project roadmap](../../blob/main/docs/documentation/development-guide.md#project-roadmap) and this is not already planned.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the use case or limitation that motivates this request.
      placeholder: e.g. "I have two EV chargers and currently the integration only supports one."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: What behavior would you like to see? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
      description: Any workarounds or alternative solutions you have evaluated.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, links, or any other relevant information.
